### ISSUE TITLE
Update release?

### ISSUE THREAD

**Issue by ArmeF97** [bettergram/bettergram#7]
Is it possible to update bettergram? I have the 1.3.9 version...

**Comment by NabiKAZ** [comment]
And 1.5.7 with poll feature.

**Comment by gilmanov-ildar** [comment]
I have published the latest build on our Telegram group

**Comment by ArmeF97** [comment]
So one must be in your group to download?

**Comment by gilmanov-ildar** [comment]
@dimqua , Are you serious? We do not violate the GPL license. All the source codes are available here, on  GItHub, you can build the application on Linux, macOS and Windows from this source code.

And about publishing the binary files, we publish it only at the Bettergram group now, instead of our official site, because we lost our partner and good man - Max Bloom. We need time to put things in order. And after this we will continue publishing the binary files to our site.

**Comment by dimqua** [comment]
> We need time to put things in order. And after this we will continue publishing the binary files to our site.

Good to know. Thanks for the great app!

**Comment by NabiKAZ** [comment]
@gilmanov-ildar 
In your site wrote:
http://www.t.me/bettergramapp
But in telegram get this error:
```
Username bettergramapp not found.
```

**Comment by NabiKAZ** [comment]
How can I download latest binary version for windows?

**Comment by gilmanov-ildar** [comment]
[Bettergram 1.5.0 for Windows](https://drive.google.com/open?id=1ZIw5ZvfwFXY4cKD-QyLmDIzpOCOtXP2j)

[Bettergram 1.5.0 for Linux](https://drive.google.com/open?id=148RvggnYNa1GwyuR2BThdoKWC0p2nCwU)

**Comment by NabiKAZ** [comment]
@gilmanov-ildar But it's not includes new features such as separate users and bots tabs feature!
